### ISSUE TITLE
Update to API v5 release

### ISSUE THREAD

**Issue by randombyte-developer** [djxy/MultiScripts#2]
```
> sponge version
[13:58:58 INFO]: SpongeVanilla
    Minecraft: 1.10.2
    SpongeAPI: 5.1.0-SNAPSHOT-323db46
    SpongeVanilla: 1.10.2-5.1.0-BETA-366
```
Crashes on startup with this plugin: http://pastebin.com/5aQfvBMY

**Comment by djxy** [comment]
Yes, no problem. I will do that.

**Comment by djxy** [comment]
I don't find this class in the Javadocs

**Comment by djxy** [comment]
I have this class `org.spongepowered.api.world.extent.worker.procedure.BiomeAreaVisitor`

**Comment by randombyte-developer** [comment]
I didn't write code. I just dropped the jar in mods folder and started the server.

**Comment by djxy** [comment]
Okay, thanks. I will check that.

**Comment by djxy** [comment]
@randombyte-developer I fixed it. You can find the release for API 5.1.0
